export function generateMappings(tileType){
    return {
   0: () => [
    sprite(`${tileType}-tileset`, { anim: "tl" }),
    area(),
    body({ isStatic: true }),
    offscreen(),
  ],
  1: () => [
    sprite(`${tileType}-tileset`, { anim: "tm" }),
    area(),
    body({ isStatic: true }),
    offscreen(),
  ],
  2: () => [
    sprite(`${tileType}-tileset`, { anim: "tr" }),
    area(),
    body({ isStatic: true }),
    offscreen(),
  ],
  3: () => [
    sprite(`${tileType}-tileset`, { anim: "ml" }),
    area(),
    body({ isStatic: true }),
    offscreen(),
  ],
  4: () => [sprite(`${tileType}-tileset`, { anim: "mm" }), offscreen()],
  5: () => [
    sprite(`${tileType}-tileset`, { anim: "mr" }),
    area(),
    body({ isStatic: true }),
    offscreen(),
  ],
  6: () => [sprite(`${tileType}-tileset`, { anim: "bl" }), offscreen()],
  7: () => [sprite(`${tileType}-tileset`, { anim: "bm" }), offscreen()],
  8: () => [sprite(`${tileType}-tileset`, { anim: "br" }), offscreen()],
  9: () => [
    sprite(`${tileType}-oneway-tileset`, { anim: "tl" }),
    area({ shape: new Rect(vec2(0), 16, 3) }),
    "passthrough",
    body({ isStatic: true }),
    offscreen(),
  ],
  a: () => [
    sprite(`${tileType}-oneway-tileset`, { anim: "tm" }),
    area({ shape: new Rect(vec2(0), 16, 3) }),
    "passthrough",
    body({ isStatic: true }),
    offscreen(),
  ],
  b: () => [
    sprite(`${tileType}-oneway-tileset`, { anim: "tr" }),
    area({ shape: new Rect(vec2(0), 16, 3) }),
    "passthrough",
    body({ isStatic: true }),
    offscreen(),
  ],
  c: () => [
    sprite(`${tileType}-oneway-tileset`, { anim: "ml" }),
    offscreen(),
  ],
  d: () => [
    sprite(`${tileType}-oneway-tileset`, { anim: "mm" }),
    offscreen(),
  ],
  e: () => [
    sprite(`${tileType}-oneway-tileset`, { anim: "mr" }),
    offscreen(),
  ],
  o: () => [sprite("bridge"), area(), body({ isStatic: true }), offscreen()],
  "@": () => [sprite("coin"), area(), "coin", offscreen()],
  j: () => [sprite('block'), area(), body({ isStatic: true }), offscreen(), scale(0.7)],
  z: () => [
    sprite(`rock-tileset`, { anim: "tl" }),
    area(),
    body({ isStatic: true }),
    offscreen(),
  ],
  x: () => [
    sprite(`rock-tileset`, { anim: "tm" }),
    area(),
    body({ isStatic: true }),
    offscreen(),
  ],
  f: () => [
    sprite(`rock-tileset`, { anim: "tr" }),
    area(),
    body({ isStatic: true }),
    offscreen(),
  ],
  v: () => [
    sprite(`rock-tileset`, { anim: "ml" }),
    area(),
    body({ isStatic: true }),
    offscreen(),
  ],
  p: () => [sprite(`rock-tileset`, { anim: "mm" }), offscreen()],
  n: () => [
    sprite(`rock-tileset`, { anim: "mr" }),
    area(),
    body({ isStatic: true }),
    offscreen(),
  ],
  m: () => [sprite(`rock-tileset`, { anim: "bl" }), offscreen()],
  k: () => [sprite(`rock-tileset`, { anim: "bm" }), offscreen()],
  l: () => [sprite(`rock-tileset`, { anim: "br" }), offscreen()],
  '/': () => [
    sprite(`rock-oneway-tileset`, { anim: "tl" }),
    area({ shape: new Rect(vec2(0), 16, 3) }),
    "passthrough",
    body({ isStatic: true }),
    offscreen(),
  ],
  '|': () => [
    sprite(`rock-oneway-tileset`, { anim: "tm" }),
    area({ shape: new Rect(vec2(0), 16, 3) }),
    "passthrough",
    body({ isStatic: true }),
    offscreen(),
  ],
  r: () => [
    sprite(`rock-oneway-tileset`, { anim: "tr" }),
    area({ shape: new Rect(vec2(0), 16, 3) }),
    "passthrough",
    body({ isStatic: true }),
    offscreen(),
  ],
  t: () => [
    sprite(`rock-oneway-tileset`, { anim: "ml" }),
    offscreen(),
  ],
  q: () => [
    sprite(`rock-oneway-tileset`, { anim: "mm" }),
    offscreen(),
  ],
  h: () => [
    sprite(`rock-oneway-tileset`, { anim: "mr" }),
    offscreen(),
  ],
  g: () => [sprite('stone-bridge'), area(), body({ isStatic: true }), offscreen()]
}
}